### ISSUE TITLE
Export to YATA - Wrong Formatting

### ISSUE THREAD

**Issue by BritishBenji** [Zaeems/torn-city-table-maker#4]
YATA requires the following headers in an csv that are missing in the one provided:

strength_timestamp | speed_timestamp | defense_timestamp | dexterity_timestamp

These can all be set to the exact same timestamp as "total_timestamp" (which is still required) as far as I can tell, but it's unfortunately fairly specific

**Comment by Zaeems** [comment]
Hey @BritishBenji , when I originally made this tool there were no stat-specific timestamps. 
I'll look into this when I get a chance.

**Comment by Zaeems** [comment]
Added missing timestamps
